### ISSUE TITLE
SHA256 HMAC

### ISSUE THREAD

**Issue by websocket98765** [kste/sha256_avx#3]
This is very cool. Do you know of a AVX2 SHA256 _HMAC_? Every version I find is not HMAC.

**Comment by kste** [comment]
I'm not aware of any. However, in our SPHINCS+ code I've added a version of this code (https://github.com/sphincs/sphincsplus/blob/master/sha256-avx2/sha256avx.c) which can hash arbitrary length messages (probably should merge this in here). Using this it should be quite easy to construct SHA256 HMAC processing 8 blocks in parallel.

**Comment by websocket98765** [comment]
Thanks for the lead. 

The SPINCS project looks very interesting btw!
